"""SQL backend: dialect-neutral guard over PEP 249 connections."""

from .dialects import (
    DIALECTS,
    GENERIC_ANSI,
    MSSQL,
    MYSQL,
    ORACLE,
    POSTGRESQL,
    SQLITE,
    Dialect,
    dialect_for,
    generic_ansi,
)
from .guard import (
    AttachedGuard,
    SqlPredicate,
    assert_guard_current,
    filter_visible_ids,
    flag_predicate,
    guard_for_connection,
    is_record_visible,
    load_guard,
    normal_record_predicate,
    not_in_span_predicate,
    span_sources,
    status,
    table_columns,
    table_exists,
)
from . import sqlite

__all__ = [
    "Dialect",
    "DIALECTS",
    "SQLITE",
    "POSTGRESQL",
    "MYSQL",
    "MSSQL",
    "ORACLE",
    "GENERIC_ANSI",
    "generic_ansi",
    "dialect_for",
    "SqlPredicate",
    "AttachedGuard",
    "flag_predicate",
    "not_in_span_predicate",
    "normal_record_predicate",
    "span_sources",
    "table_exists",
    "table_columns",
    "load_guard",
    "guard_for_connection",
    "assert_guard_current",
    "filter_visible_ids",
    "is_record_visible",
    "status",
    "sqlite",
]
